apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-delete-tasks
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-delete-tasks
  ports:
    - port: {{ .Values.deleteTask.ServicePort }}
      targetPort: {{ .Values.deleteTask.port }}
