apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-micro-ui
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-micro-ui
  ports:
    - port: {{ .Values.ui.ServicePort }}
      targetPort: {{ .Values.ui.port }}
