apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-add-tasks
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-todo-add-tasks
  ports:
    - port: {{ .Values.addTask.ServicePort }}
      targetPort: {{ .Values.addTask.port }}
